# Put general config stuff here
# Here's a list of every variable: https://wiki.hyprland.org/Configuring/Variables/


input {
    scroll_factor = 0.6
    sensitivity = 0.5
    accel_profile = adaptive
}
